- uses: actions/checkout@v3

- uses: actions/setup-go@v3
  with:
    go-version: '1.19'
- run: go test -v -coverprofile=profile.cov ./...

- uses: shogo82148/actions-goveralls@v1.7.0
  with:
    path-to-profile: profile.cov